services:
  node:
    build:
      context: ./
      dockerfile: docker/node/Dockerfile
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    ports:
      - "80:3000"
      - "81:3001"
    hostname: kolab.localhost

  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    volumes:
      - ./docker/mysql/data:/var/lib/mysql
    environment:
      MYSQL_DATABASE: docker
      MYSQL_ROOT_PASSWORD: root
